/*
 * (c) Lanaya
 */
package ui_menu;

import game.Game;

/**
 *
 * @author Lanaya
 */
public class OptionsMenu extends javax.swing.JPanel {

    private final Game game;
    
    public OptionsMenu(Game game) {
        this.game = game;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        acceptButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        resolutionSelector = new javax.swing.JComboBox<>();
        resolutionLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        acceptButton.setText("Accept");
        acceptButton.addActionListener(new ui_action.OptionsAccept(game, resolutionSelector));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 20, 20, 0);
        add(acceptButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new ui_action.OptionsCancel(game));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 18, 20, 20);
        add(cancelButton, gridBagConstraints);

        resolutionSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1366x768", "1440x900", "1920x1080", "2560x1440" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 4, 0, 20);
        add(resolutionSelector, gridBagConstraints);

        resolutionLabel.setText("Resolution:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 31, 0, 0);
        add(resolutionLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel resolutionLabel;
    private javax.swing.JComboBox<String> resolutionSelector;
    // End of variables declaration//GEN-END:variables
}
