/*
 * (c) Lanaya
 */
package ui_menu;

import game.Game;
import ui_action.SaveGameCancel;

/**
 *
 * @author Lanaya
 */
public class SaveGameMenu extends javax.swing.JPanel {

    private final Game game;
    
    public SaveGameMenu(Game game) {
        this.game = game;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        savePathField = new javax.swing.JTextField();
        savePathLabel = new javax.swing.JLabel();
        buttonAcceptSave = new javax.swing.JButton();
        buttonCancelSave = new javax.swing.JButton();

        setOpaque(false);

        savePathField.setText("savegame01");

        savePathLabel.setForeground(new java.awt.Color(255, 255, 255));
        savePathLabel.setText("Enter save game name:");

        buttonAcceptSave.setText("OK");
        buttonAcceptSave.addActionListener(new ui_action.SaveGameAccept(game, this));

        buttonCancelSave.setText("CANCEL");
        buttonCancelSave.addActionListener(new SaveGameCancel(game));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(savePathLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(savePathField, javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addComponent(buttonAcceptSave)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(buttonCancelSave)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(savePathLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savePathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAcceptSave)
                    .addComponent(buttonCancelSave)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcceptSave;
    private javax.swing.JButton buttonCancelSave;
    private javax.swing.JTextField savePathField;
    private javax.swing.JLabel savePathLabel;
    // End of variables declaration//GEN-END:variables

    public String getTextFromField() {
        return savePathField.getText();
    }

}
